version: "3"
services:
    this_jupyter:
        image: jupyter/datascience-notebook
        ports:
            - 8888:8888
        volumes:
            - .:/home/jovyan
        command: start-notebook.sh --NotebookApp.token=""   
